/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-02-19 05:28:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.imageboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class imageboardWriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".imgTable1{\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<form name=\"imageboardWriteForm\" method=\"post\" enctype=\"multipart/form-data\" action=\"../imageboard/imageboardWrite.do\">\r\n");
      out.write("\t\t<table class=\"imgTable1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\">상품코드</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"imageId\" id=\"imageId\" size=\"40\" value=\"img_\">\r\n");
      out.write("\t\t\t\t\t<div id=\"imageIdDiv\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\">상품명</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"imageName\" id=\"imageName\" size=\"50\" placeholder=\"상품명 입력\">\r\n");
      out.write("\t\t\t\t\t<div id=\"imageNameDiv\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\" >단가</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"imagePrice\" id=\"imagePrice\" size=\"30\" placeholder=\"단가 입력\">\r\n");
      out.write("\t\t\t\t\t<div id=\"imagePriceDiv\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"70\">개수</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"imageQty\" id=\"imageQty\" size=\"30\" placeholder=\"개수 입력\">\r\n");
      out.write("\t\t\t\t\t<div id=\"imageQtyDiv\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td  width=\"70\">내용</td>\r\n");
      out.write("\t\t\t\t<td><textarea name=\"imageContent\" id=\"imageContent\" rows=\"15\" cols=\"50\" placeholder=\"내용 입력\"></textarea>\r\n");
      out.write("\t\t\t\t\t<div id=\"imageContentDiv\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" name=\"image1\" id=\"image1\" size=\"50\">\r\n");
      out.write("\t\t\t\t\t<div id=\"image1Div\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input id=\"imageboardWriteFormBtn\" type=\"button\" value=\"이미지등록\">\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('#imageboardWriteFormBtn').click(function(){\r\n");
      out.write("\t$('#imageIdDiv').empty();\r\n");
      out.write("\t$('#imageNameDiv').empty();\r\n");
      out.write("\t$('#imagePriceDiv').empty();\r\n");
      out.write("\t$('#imageQtyDiv').empty();\r\n");
      out.write("\t$('#imgaeContentDiv').empty();\r\n");
      out.write("\t$('#image1Div').empty();\r\n");
      out.write("\t\r\n");
      out.write("\tif($('#imageId').val()=='img_' || $('#imageId').val()==''){\r\n");
      out.write("\t\t$('#imageIdDiv').text('상품코드를 입력하세요');\r\n");
      out.write("\t\t$('#imageIdDiv').css('color','red');\r\n");
      out.write("\t\t$('#imageIdDiv').css('font-size','8pt');\r\n");
      out.write("\t\t$('#imageIdDiv').css('font-weight','bold');\r\n");
      out.write("\t}else if($('#imageName').val()==''){\r\n");
      out.write("\t\t$('#imageNameDiv').text('상품명을 입력하세요');\r\n");
      out.write("\t\t$('#imageNameDiv').css('color','red');\r\n");
      out.write("\t\t$('#imageNameDiv').css('font-size','8pt');\r\n");
      out.write("\t\t$('#imageNameDiv').css('font-weight','bold');\r\n");
      out.write("\t}else if($('#imagePrice').val()==''){\r\n");
      out.write("\t\t$('#imagePriceDiv').text('단가를 입력하세요');\r\n");
      out.write("\t\t$('#imagePriceDiv').css('color','red');\r\n");
      out.write("\t\t$('#imagePriceDiv').css('font-size','8pt');\r\n");
      out.write("\t\t$('#imagePriceDiv').css('font-weight','bold');\r\n");
      out.write("\t}else if($('#imageQty').val() == '' ){\r\n");
      out.write("\t\t$('#imageQtyDiv').text('개수를 입력하세요');\r\n");
      out.write("\t\t$('#imageQtyDiv').css('color','red');\r\n");
      out.write("\t\t$('#imageQtyDiv').css('font-size','8pt');\r\n");
      out.write("\t\t$('#imageQtyDiv').css('font-weight','bold');\r\n");
      out.write("\t}else if($('#imageContent').val() == ''){\r\n");
      out.write("\t\t$('#imageContentDiv').text('내용을 입력하세요');\r\n");
      out.write("\t\t$('#imageContentDiv').css('color','red');\r\n");
      out.write("\t\t$('#imageContentDiv').css('font-size','8pt');\r\n");
      out.write("\t\t$('#imageContentDiv').css('font-weight','bold');\r\n");
      out.write("\t}else if($('#image1').val() == ''){\r\n");
      out.write("\t\t$('#image1Div').text('이미지 파일이 없습니다');\r\n");
      out.write("\t\t$('#image1Div').css('color','red');\r\n");
      out.write("\t\t$('#image1Div').css('font-size','8pt');\r\n");
      out.write("\t\t$('#image1Div').css('font-weight','bold');\r\n");
      out.write("\t}else\r\n");
      out.write("\t\t$('form[name=imageboardWriteForm]').submit();\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
